@server = https://ec3-barzola.onrender.com
@api = {{server}}/api/ec3

################ Categorias: ################
###
GET {{api}}/categorias
###
POST {{api}}/categorias
Content-Type: application/json

{"nombre": "Repuesto de Bateria"}
################ Instrumentos: ################
###
GET {{api}}/instrumentos
###
POST {{api}}/instrumentos
Content-Type: application/json

{"nombre": "Piano", "categoria": "http://localhost/api/ec3/categorias/1"}
###
GET {{api}}/instrumentos/1/categoria
###
GET {{api}}/instrumentos?sort=nombre,desc